-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_profile_id uuid,
  business_name text NOT NULL,
  contact_name text NOT NULL,
  main_email text NOT NULL,
  main_phone text,
  rif_or_id text,
  city text,
  zone text,
  address text,
  status USER-DEFINED NOT NULL DEFAULT 'pending_payment'::client_status,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  billing_email text,
  administrative_contact text,
  invitation_sent_at timestamp with time zone,
  access_enabled_at timestamp with time zone,
  access_enabled_by uuid,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_owner_profile_id_fkey FOREIGN KEY (owner_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT clients_access_enabled_by_fkey FOREIGN KEY (access_enabled_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.incidents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  subscription_id uuid,
  reported_by uuid,
  assigned_to uuid,
  title text NOT NULL,
  description text NOT NULL,
  priority USER-DEFINED NOT NULL DEFAULT 'medium'::incident_priority,
  status USER-DEFINED NOT NULL DEFAULT 'open'::incident_status,
  channel USER-DEFINED NOT NULL DEFAULT 'dashboard'::incident_channel,
  reported_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone,
  resolution_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT incidents_pkey PRIMARY KEY (id),
  CONSTRAINT incidents_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT incidents_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT incidents_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.profiles(id),
  CONSTRAINT incidents_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  company_name text NOT NULL,
  email text NOT NULL,
  phone text,
  city text,
  service_zone text,
  plan_interest_id uuid,
  source text,
  status USER-DEFINED NOT NULL DEFAULT 'new'::lead_status,
  notes text,
  converted_client_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  payment_method USER-DEFINED,
  reference_code text,
  proof_file_path text,
  submitted_at timestamp with time zone DEFAULT now(),
  auth_user_id uuid,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_plan_interest_id_fkey FOREIGN KEY (plan_interest_id) REFERENCES public.plans(id),
  CONSTRAINT leads_converted_client_id_fkey FOREIGN KEY (converted_client_id) REFERENCES public.clients(id),
  CONSTRAINT leads_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  subscription_id uuid NOT NULL,
  amount_usd numeric NOT NULL CHECK (amount_usd >= 0::numeric),
  payment_method USER-DEFINED NOT NULL,
  reference_code text,
  proof_file_url text,
  proof_file_path text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status,
  paid_at timestamp with time zone,
  submitted_at timestamp with time zone,
  verified_at timestamp with time zone,
  verified_by uuid,
  admin_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT payments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT payments_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL UNIQUE,
  price_usd numeric NOT NULL CHECK (price_usd >= 0::numeric),
  monthly_visit_limit integer,
  is_unlimited_visits boolean NOT NULL DEFAULT false,
  response_time_min_hours integer,
  response_time_max_hours integer,
  remote_support_label text,
  maintenance_label text,
  cloud_backup_label text,
  local_backup_label text,
  backup_verification_label text,
  recovery_validation_label text,
  advisory_label text,
  monitoring_label text,
  scope_label text,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  phone text,
  role USER-DEFINED NOT NULL DEFAULT 'client'::app_role,
  avatar_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.service_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  subscription_id uuid,
  visit_id uuid,
  incident_id uuid,
  created_by uuid,
  title text NOT NULL,
  summary text NOT NULL,
  work_performed text,
  recommendations text,
  file_url text,
  file_path text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT service_reports_pkey PRIMARY KEY (id),
  CONSTRAINT service_reports_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT service_reports_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT service_reports_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT service_reports_incident_id_fkey FOREIGN KEY (incident_id) REFERENCES public.incidents(id),
  CONSTRAINT service_reports_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending_payment'::subscription_status,
  start_date date,
  end_date date,
  renewal_due_date date,
  activated_at timestamp with time zone,
  activated_by uuid,
  price_snapshot_usd numeric NOT NULL CHECK (price_snapshot_usd >= 0::numeric),
  visit_limit_snapshot integer,
  is_unlimited_snapshot boolean NOT NULL DEFAULT false,
  visit_used_count integer NOT NULL DEFAULT 0 CHECK (visit_used_count >= 0),
  visit_available_count integer NOT NULL DEFAULT 0 CHECK (visit_available_count >= 0),
  days_remaining integer NOT NULL DEFAULT 0,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id),
  CONSTRAINT subscriptions_activated_by_fkey FOREIGN KEY (activated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.visits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  subscription_id uuid,
  assigned_to uuid,
  visit_type USER-DEFINED NOT NULL DEFAULT 'included'::visit_type,
  status USER-DEFINED NOT NULL DEFAULT 'scheduled'::visit_status,
  scheduled_start timestamp with time zone NOT NULL,
  scheduled_end timestamp with time zone,
  completed_at timestamp with time zone,
  title text NOT NULL,
  description text,
  internal_notes text,
  client_visible_notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT visits_pkey PRIMARY KEY (id),
  CONSTRAINT visits_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT visits_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT visits_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
  CONSTRAINT visits_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);